pipeline:
  publish-docker-image:
      image: plugins/docker
      registry: quay.io
      repo: quay.io/presslabs/github-clubhouse-sync
      username: presslabs+drone
      secrets:
        - source: QUAY_TOKEN
          target: DOCKER_PASSWORD

  deploy:
    image: gcr.io/pl-infra/kluster-deploy:latest
    pull: true
    secrets:
      - GOOGLE_CREDENTIALS
    commands:
      - /usr/local/bin/setup-credentials-helper.sh
      - cd /src/production/github-clubhouse-sync
      - make
